### ISSUE TITLE
After upgrading from 4.13.1 to 4.14.0, my scripts don't compile anymore.

### ISSUE THREAD

**Issue by UweKeim** [oleg-shilo/cs-script#451]
```
C:\>dotnet tool install --global cs-script.cli
Das Tool "cs-script.cli" wurde erfolgreich von Version 4.13.1 auf Version 4.14.0 aktualisiert.
```

Then:

```
C:\P\zp-17.1\ZetaProducerMain\Source>c:\P\zp-17.1\ZetaProducerMain\Deploy\Publish\ToLocally\move-externals.cmd

PUSHD

CD /d c:\P\zp-17.1\ZetaProducerMain\Deploy\Publish\ToLocally\

call "c:\P\zp-17.1\ZetaProducerMain\Deploy\Publish\ToLocally\\..\..\..\..\_References\update-submodules.cmd"
Submodule zurücksetzen...
Verarbeite Submodul: zeta-shared-ci-assets
HEAD is now at c67ff84 Merge branch 'chore/deploy-trigger-meta'
Aktualisiere Submodule...
Alle Submodule wurden zurückgesetzt und aktualisiert.
WARNING: Cannot find .NET 10 SDK required for `dotnet` compiler engine. Switching compiler to `roslyn` instead.
To remove this warning either install .NET 10 SDK or set the default compiler engine to `roslyn` with
  css -config:set:DefaultCompilerEngine=roslyn.
Note, Roslyn engine has some fundamental limitation.--------
Error: Specified file could not be compiled.

c:\P\zp-17.1\_References\Submodules\zeta-shared-ci-assets\DevelopmentTools\CentralScripts\Afx.cs(51,0): error CS7021: Cannot declare namespace in script code
c:\P\zp-17.1\_References\Submodules\zeta-shared-ci-assets\DevelopmentTools\CentralScripts\AppOfflineUtilities.cs(7,0): error CS7021: Cannot declare namespace in script code
```

I'm a bit in a hurry, will add details later.
